### ISSUE TITLE
Can't create new Schema

### ISSUE THREAD

**Issue by wkiser** [Landoop/schema-registry-ui#14]
When I try to create a new schema I get an alert with the message: "Selected Case Number is 1". The new schema does not seem to be registered after this happens.

The generated curl command works well though.

**Comment by request-eduardo** [comment]
I am still getting this error when using the most recent version uploaded to docker, which is supposed to contain this bugfix. I am having to run the generated curl manually because it still shows up an alertbox with Selected Case Number is 1 and ends up doing nothing

**Comment by chdask** [comment]
Hi @request-eduardo, 

It seems that it was merged to master but not in release. So this will be available to v0.7.1 later today when the release is completed. 
It's deployed here: https://schema-registry-ui.landoop.com

**Comment by request-eduardo** [comment]
Thanks a lot, I appreciate the effort



 Enviado con Mailtrack
<https://mailtrack.io/install?source=signature&lang=es&referral=eduardo@request.cl&idSignature=23>

2016-10-12 10:25 GMT-03:00 Christina Daskalaki <notifications@github.com>:

**Comment by request-eduardo** [comment]
Hi @chdask 

I suppose you had trouble again building v0.7.1 for docker... The bug is still there

Guess I'll stay checking
