### ISSUE TITLE
Is "Evolve Schema" intended to create a new version of a schema?

### ISSUE THREAD

**Issue by Analect** [Landoop/schema-registry-ui#16]
I've been using the kafka-topics-ui and schema-registry-ui over recent weeks and find them very useful.

As per below, I tried editing the field "private" so that it became a 'string' from an 'int'.
On hittiing 'evolve schema' ... is that intended to be the equivalent of a `curl -X POST http://schema-registry:8081/subjects/my-connector/versions -d '{ ... }'` ... in order to create a new version of the schema?

![image](https://cloud.githubusercontent.com/assets/4063815/19033733/d66c2c68-8957-11e6-8cb4-2b284c2e54f7.png)

I couldn't get it to work ... although, admittedly ... when I try to generate a new schema using the schema-registry API ... it also fails with a 409 conflict.  I even tried to delete the topic .. in case this conflict was being caused by existing entries.  Do you think the change I'm making to the 'private' field qualifies as a legitimate schema change?

```
curl -i -X POST -H "Content-Type: application/json" http://localhost:8081/subjects/ckan-meta-package-value/versions --data '{"schema": "{\"type\":\"record\",\"name\":\"package\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"title\",\"type\":[\"null\",\"string\"]},{\"name\":\"version\",\"type\":[\"null\",\"string\"]},{\"name\":\"url\",\"type\":[\"null\",\"string\"]},{\"name\":\"notes\",\"type\":[\"null\",\"string\"]},{\"name\":\"license_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"revision_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"author\",\"type\":[\"null\",\"string\"]},{\"name\":\"author_email\",\"type\":[\"null\",\"string\"]},{\"name\":\"maintainer\",\"type\":[\"null\",\"string\"]},{\"name\":\"maintainer_email\",\"type\":[\"null\",\"string\"]},{\"name\":\"state\",\"type\":[\"null\",\"string\"]},{\"name\":\"type\",\"type\":[\"null\",\"string\"]},{\"name\":\"owner_org\",\"type\":[\"null\",\"string\"]},{\"name\":\"private\",\"type\":[\"null\",\"string\"]},{\"name\":\"metadata_modified\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\"}]},{\"name\":\"creator_user_id\",\"type\":[\"null\",\"string\"]}],\"connect.name\":\"package\"}"}'
HTTP/1.1 100 Continue

HTTP/1.1 409 Conflict
Date: Mon, 03 Oct 2016 10:29:33 GMT
Content-Type: application/vnd.schemaregistry.v1+json
Content-Length: 93
Server: Jetty(9.2.12.v20150709)

{"error_code":409,"message":"Schema being registered is incompatible with the latest schema"}
```
It seems the 'schema-registry API' doesn't allow for deleting schemas?

Also, does the output from the schema window (below) qualify as an '*.avsc' file-type ... and is a simple copy and paste?

![image](https://cloud.githubusercontent.com/assets/4063815/19034761/418bb342-895d-11e6-9713-bdf752fc8e65.png)

Thanks.

**Comment by Antwnis** [comment]
Read: 

https://docs.oracle.com/cd/E26161_02/html/GettingStartedGuide/schemaevolution.html

```You cannot change a field's data type. If you have decided that a field should be some data type other than what it was originally created using, then add a whole new field to your schema that uses the appropriate data type.```

> It seems the 'schema-registry API' doesn't allow for deleting schemas?

That is correct. Schema's are stored into a Kafka topic, and Kafka does not allow deletion of messages 

> Also, does the output from the schema window (below) qualify as an '*.avsc' file-type ... and is a simple copy and paste?

That is correct

**Comment by Antwnis** [comment]
Just to be a little more accurate - schema evolution allows *widening* types

i.e. https://github.com/Landoop/landoop-avro-generator/blob/master/src/main/java/com.landoop.avrogenerator/messages/AvroEvolutionWiden.java

But i've never tested widening and Int -> String
Int -> Long though should be OK

**Comment by Analect** [comment]
Thanks @Antwnis .... I clearly should have done a more thorough reading of the docs!
