### ISSUE TITLE
Docker image broken by change to support multiple environments

### ISSUE THREAD

**Issue by mtranter** [Landoop/schema-registry-ui#29]
The run.sh script in the docker folder  longer updates the JS correctly to provide the SCHEMAREGISTRY_URL.

From docker/run.js
```
else
    echo "Setting Schema Registry URL to $SCHEMAREGISTRY_URL."
    sed -e 's|^\s*var SCHEMA_REGISTRY =.*|  var SCHEMA_REGISTRY = "'"$SCHEMAREGISTRY_URL"'";|' \
        -i /schema-registry-ui/combined.js
fi
```

**Comment by andmarios** [comment]
Thanks for the heads up! It eluded our testing. I fixed it and the working image is already up on docker hub. Sorry for any inconvenience this caused.

Feel free to re-open if it still doesn't work.

**Comment by mtranter** [comment]
Thank you for the rapid response!
