### ISSUE TITLE
Problem with subjects list while fetching subjects

### ISSUE THREAD

**Issue by rkluszczynski** [Landoop/schema-registry-ui#31]
Hello!

First of all, I wanna say that schema-registry-ui looks really nice and have nice feature like diff. At the moment we are thinking how to visualize schemas stored in schema-registry.

I have tried to run it, but I have problem with subject lists which contains only empty entries. I think, this is because of:

https://github.com/Landoop/schema-registry-ui/blob/master/src/factories/schema-registry-factory.js#L454

Where according to Confluent API:

http://docs.confluent.io/3.1.1/schema-registry/docs/api.html#get--subjects-(string-%20subject)-versions-(versionId-%20version)

answer does not contain any JSON field named "subject".

What version of schema-registry was checked with schema-registry-ui?
If that is the case, maybe subject could be somehow read from URL or in other way instead from the response.

What do you think?
Do you have any suggestion?

Kind regards,
Rafal Kluszczynski

**Comment by Antwnis** [comment]
Just tested on a CP 3.1.1 schema-registry and it works on our testing environments

To debug it if you open Chrome Dev tools and check the Network tab you'll see the subjects/ request. Does that respond with the subjects that are already registered in the schema-registry ?

For example - see how the response would look like on our servers

    curl -X GET https://schema-registry.demo.landoop.com/subjects/

**Comment by Antwnis** [comment]
Hi Rafal, did you have a change to look at it ?!

According to the Confluent API - there is no "subject" in the response. However as you can see in the following API call - the 'subject' is actually part of the response
 
http://cloudera.landoop.com:13032/api/schema-registry/subjects/device-measurements-topic-key/versions/1

**Comment by rkluszczynski** [comment]
Hello @Antwnis,
sorry for late response. Everything is

**Comment by Antwnis** [comment]
Hi Rafal. Everything is ... ?

**Comment by rkluszczynski** [comment]
@Antwnis Your quick:) I've udpated the comment just a second ago:)

**Comment by Antwnis** [comment]
You are welcome. Thanks a lot for the feedback !
