### ISSUE TITLE
schema registry https support?

### ISSUE THREAD

**Issue by simplesteph** [Landoop/schema-registry-ui#40]
I have enabled https connections on my schema registry but it's within a private domain. 
How do I specify the truststore or pem certificates so that the schema-registry-ui can connect to `https://my-schema-registry.example.com/` ?

**Comment by andmarios** [comment]
The schema registry UI runs in your browser (it's an angular app), so essentially it is your browser that connects to your schema registry.

Thus you need to add the certificates to your browser.

**Comment by simplesteph** [comment]
@andmarios that's correct, unless we use `PROXY=true` in the docker image (which we do). How would we work that out in that case?

**Comment by andmarios** [comment]
I just added an option to do that: `PROXY_SKIP_VERIFY`. It is used in conjunction with `PROXY`. I.e:

    docker run \
        -e "SCHEMAREGISTRY_URL=https://schema.registry.url" \
        -e PROXY=true\
        -e PROXY_SKIP_VERIFY=true\
        landoop/schema-registry-ui

I added it to both the schema-registry-ui and kafka-topics-ui, at the latest docker images (make sure to docker pull before trying).

Hope it works for you now. I couldn't test thoroughly, so please confirm if it is.
Btw, we added tags to our images. E.g: https://hub.docker.com/r/landoop/schema-registry-ui/tags/

**Comment by simplesteph** [comment]
Excellent thanks I'll test first thing tomorrow

**Comment by simplesteph** [comment]
looks like it's working! Would be even better to add an option to pass in the trust certificate but I can live with that at the moment :)

**Comment by andmarios** [comment]
Hmm, the caddy server uses the system certificates. To my experience it would be error prone to add code to update the system certificates, so we will avoid it for now.

Something you may want to try though, is to replace the certificates file of the container with your certificate, or even better your system's certificate chain.
Maybe something like this:

    docker run -v custom.crt:/etc/ssl/certs/ca-certificates.crt ...

**Comment by simplesteph** [comment]
@andmarios you're right. The containers don't inherit the host certificates though, so mapping volumes would be the best way. I'll give this a go! I'll let you close this issue when you've released a new version of schema-registry-ui :)

**Comment by Antwnis** [comment]
Stephane - Will be closing this issue as we just released 0.9.1 just now
@andmarios can you update README.md with the PROXY_SKIP_VERIFY option / some documentation and close this issue please ?

**Comment by andmarios** [comment]
Closing. Feel free to comment if something doesn't work as expected.
