### ISSUE TITLE
Allow for kafka connect sink config generation

### ISSUE THREAD

**Issue by andrewstevenson** [Landoop/schema-registry-ui#5]
For example allow field selection from a topic to write to Kudu. Generate a properties from this.

**Comment by Antwnis** [comment]
This capability is now part of the https://kafka-connect-ui.landoop.com/#/select-connector

**Comment by andrewstevenson** [comment]
But I want to be able to select fields from topic when browsing the schema registry and then link into the connect ui?

**Comment by Antwnis** [comment]
Re-opening

**Comment by Antwnis** [comment]
To be available soon 📦
