### ISSUE TITLE
Support configurable port via ENV variable

### ISSUE THREAD

**Issue by eshepelyuk** [Landoop/schema-registry-ui#54]
Hello,

Could you please add a possibility to customize server port when running UI in docker via ENV variable.
E.g.

    $ docker run -e SCHEMA_REGISTRY_UI_PORT=9999 

This scenario is quite useful when one doesn't want to expose separate port for instance in `Docker Swarm` cluster, but use default proxy setting where services are routed to the same port.

**Comment by andmarios** [comment]
Hello, I added this via the `PORT` environment variable. E.g

    docker run -e PORT=10205...
