### ISSUE TITLE
only latest docker image handles the PORT environment variable

### ISSUE THREAD

**Issue by giogt** [Landoop/schema-registry-ui#71]
We are currently using the `PORT` environment variable for the docker image, that makes our life easier for the topology that we are currently using in our Kubernetes clusters.
But the `PORT` environment variable is only available in the `latest` docker image. I would like to lock the docker version down to a specific version instead of using `latest`.
Maybe you can publish a new docker image version including the `PORT` environment variable on docker hub with a specific version, such as 0.9.5 if you are going to do a next release?
What do you think?

Thank you

**Comment by andmarios** [comment]
Hi @giogt . I just released 0.9.5. :)

**Comment by Antwnis** [comment]
Closing this ticket. @giogt please re-open if it has not been addressed/fixed. Thanks for reporting it

**Comment by giogt** [comment]
Just tested it, it works. Thanks a lot, guys!
