### ISSUE TITLE
If I am using mac? how to avoid the 401? or the issue running without docker

### ISSUE THREAD

**Issue by esuarezz** [Landoop/schema-registry-ui#77]
ou will need schema-registry installed with CORS enabled.

In order to enable CORS, add in /opt/confluent-3.x.x/etc/schema-registry/schema-registry.properties

access.control.allow.methods=GET,POST,PUT,OPTIONS
access.control.allow.origin=*

**Comment by andmarios** [comment]
I'm not sure what the question is. Feel free to rephrase and reopen the issue if needed.
