### ISSUE TITLE
Prevent edit of schemas/update of compatibility from UI interface

### ISSUE THREAD

**Issue by Rancho007** [Landoop/schema-registry-ui#80]
Hello,

I have question regarding how to prevent edit or schemas or update of compatibility. I would like to restrict the usage of schema registry UI to view schema only.  Is it possible? How to achieve this?

Thank you,

Kr,
R.

**Comment by jglambed** [comment]
Hello @Rancho007,
At this moment you can only prevent users from changing the global schema compatibility.
A view only mode would be a nice addition indeed but I cannot provide you with a timeframe.

**Comment by Rancho007** [comment]
Hi @jglambed 

Thank you for quick response.
Indeed it could be interesting from the security point of view. We will eagerly wait for it :) 

Kr,
R

**Comment by fstaudt** [comment]
Would it be OK to create a pull request for this feature ?

**Comment by jglambed** [comment]
@fstaudt Pull requests are always welcome! If you have a proposal ready, go for it!

**Comment by fstaudt** [comment]
@jglambed I don't have a pull request ready yet, I just wanted to make sure that you were OK with it.
I'll start working on it.

When do you plan to release the next milestone (0.9.0) ?

**Comment by jglambed** [comment]
@Rancho007 @fstaudt I close this issue as an outcome of @fstaudt work on #87 
This is now supported with the use of readonlyMode.
