### ISSUE TITLE
Will this UI work for Confluent oss 5.1.2??

### ISSUE THREAD

**Issue by Gk8143197049** [Landoop/schema-registry-ui#81]
I wanted to check if this works for confluent 5.1.2? if yes ,can you tell what configurations do I need to use for configuring ?

THanks!!

**Comment by stheppi** [comment]
Did you try it? 
Unfortunately but this is not an issue and I will close the entry.
The readme files gives all the details on how to run it and the configuration to set:

![image](https://user-images.githubusercontent.com/2507367/54718552-ac33fb00-4b52-11e9-83f0-54148b341cef.png)

If you do encounter issues when running it, we are happy to assist.

**Comment by Gk8143197049** [comment]
@stheppi I tried with your steps and teh UI is not coming up and do we have logs to check. The UI does not pop up . below are the commands:

$npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> schema-registry-ui@0.9.5 postinstall /opt/confluent-5.1.2/schema-registry-ui
>



[xxxxxxxxx]$ npm start

> schema-registry-ui@0.9.5 start /opt/confluent-5.1.2/schema-registry-ui
> node ./node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.js --progress

Building for development
 10% building modules 1/1 modules 0 active
Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /opt/confluent-5.1.2/schema-registry-ui/dist
404s will fallback to /index.html

**Comment by stheppi** [comment]
@jglambed  ^
