### ISSUE TITLE
Connect to a schema registry that is using basic auth

### ISSUE THREAD

**Issue by pa009fa** [Landoop/schema-registry-ui#84]
We have a schema registry set up with basic authentication and want to use schema-registry-ui with it. After looking through the documentation and the code it seems like something schema-registry-ui doesn't do right now. Is this correct?

Thanks.

**Comment by jglambed** [comment]
Hello, @pa009fa 

Indeed that's something Schema Registry UI is not able to do. And not in our plans to enhance it this way.

You can connect to your protected Schema Registry by using [Lenses](www.lenses.io) which is free for devs and comes with a package of many other cool features. 

Take a look at the simple configuration here:
https://docs.lenses.io/2.3/install_setup/configuration/lenses-config.html#schema-registry
